webServer:
  name: web-server
  replicaCount: 1
  configMapName: web-server-dev-config
  image:
    repository: 390430468701.dkr.ecr.ap-south-1.amazonaws.com/webfrontend
    tag: latest
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
  containerPort: 80
  service:
    port: 80
    targetPort: 3000
    type: ClusterIP