webServer:
  name: web-server
  replicaCount: 2
  configMapName: web-server-prod-config
  image:
    repository: 390430468701.dkr.ecr.ap-south-1.amazonaws.com/webfrontend
    tag: latest
  resources:
    limits:
      memory: "400Mi"
      cpu: "400m"
  containerPort: 80
  service:
    port: 80
    targetPort: 3000
    type: ClusterIP