replicaCount: 1

image:
  repository: 390430468701.dkr.ecr.ap-south-1.amazonaws.com/modelbackend
  tag: latest

resources:
  limits:
    memory: "1Gi"
    cpu: "200m"

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

redis:
  secretName: redis-release-dev-redis-secret

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70