replicaCount: 2

image:
  repository: 390430468701.dkr.ecr.ap-south-1.amazonaws.com/modelbackend
  tag: latest

resources:
  limits:
    memory: "2Gi"
    cpu: "400m"

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

redis:
  secretName: redis-release-prod-redis-secret

autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70